# -*- coding: utf-8 -*-
import sys
#from tkinter.tix import Form

################################################################################
## Form generated from reading UI file 'RoteadorjxHyuV.ui'
##
## Created by: Qt User Interface Compiler version 6.11.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QSizePolicy, QWidget, QMainWindow)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(170, 170)
        Form.setMinimumSize(QSize(170, 170))
        Form.setMaximumSize(QSize(170, 170))
        self.router = QWidget(Form)
        self.router.setObjectName(u"router")
        self.router.setGeometry(QRect(30, 30, 130, 130))
        self.routerLabel = QLabel(self.router)
        self.routerLabel.setObjectName(u"routerLabel")
        self.routerLabel.setGeometry(QRect(40, 50, 50, 30))
        font = QFont()
        font.setFamilies([u"Arial"])
        font.setPointSize(14)
        font.setBold(True)
        self.routerLabel.setFont(font)
        self.routerLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.north_HIGH_Label = QLabel(self.router)
        self.north_HIGH_Label.setObjectName(u"north_HIGH_Label")
        self.north_HIGH_Label.setGeometry(QRect(90, 0, 40, 20))
        font1 = QFont()
        font1.setFamilies([u"Andale Mono"])
        font1.setPointSize(10)
        self.north_HIGH_Label.setFont(font1)
        self.south_HIGH_Label = QLabel(self.router)
        self.south_HIGH_Label.setObjectName(u"south_HIGH_Label")
        self.south_HIGH_Label.setGeometry(QRect(82, 110, 40, 20))
        self.south_HIGH_Label.setFont(font1)
        self.south_LOW_Label = QLabel(self.router)
        self.south_LOW_Label.setObjectName(u"south_LOW_Label")
        self.south_LOW_Label.setGeometry(QRect(20, 110, 40, 20))
        self.south_LOW_Label.setFont(font1)
        self.weast_LOW_Label = QLabel(self.router)
        self.weast_LOW_Label.setObjectName(u"weast_LOW_Label")
        self.weast_LOW_Label.setGeometry(QRect(1, 70, 40, 20))
        self.weast_LOW_Label.setFont(font1)
        self.weast_HIGH_Label = QLabel(self.router)
        self.weast_HIGH_Label.setObjectName(u"weast_HIGH_Label")
        self.weast_HIGH_Label.setGeometry(QRect(1, 20, 40, 20))
        self.weast_HIGH_Label.setFont(font1)
        self.north_LOW_Label = QLabel(self.router)
        self.north_LOW_Label.setObjectName(u"north_LOW_Label")
        self.north_LOW_Label.setGeometry(QRect(40, 0, 40, 20))
        self.north_LOW_Label.setFont(font1)
        self.east_HIGH_Label = QLabel(self.router)
        self.east_HIGH_Label.setObjectName(u"east_HIGH_Label")
        self.east_HIGH_Label.setGeometry(QRect(90, 40, 40, 20))
        self.east_HIGH_Label.setFont(font1)
        self.east_LOW_Label = QLabel(self.router)
        self.east_LOW_Label.setObjectName(u"east_LOW_Label")
        self.east_LOW_Label.setGeometry(QRect(90, 90, 40, 20))
        self.east_LOW_Label.setFont(font1)
        self.out_north_HIGH = QWidget(Form)
        self.out_north_HIGH.setObjectName(u"out_north_HIGH")
        self.out_north_HIGH.setGeometry(QRect(115, 0, 6, 30))
        self.in_north_HIGH = QWidget(Form)
        self.in_north_HIGH.setObjectName(u"in_north_HIGH")
        self.in_north_HIGH.setGeometry(QRect(124, 0, 20, 30))
        self.out_weast_HIGH = QWidget(Form)
        self.out_weast_HIGH.setObjectName(u"out_weast_HIGH")
        self.out_weast_HIGH.setGeometry(QRect(0, 77, 30, 6))
        self.in_weast_HIGH = QWidget(Form)
        self.in_weast_HIGH.setObjectName(u"in_weast_HIGH")
        self.in_weast_HIGH.setGeometry(QRect(0, 53, 30, 20))
        self.in_east_LOW = QWidget(Form)
        self.in_east_LOW.setObjectName(u"in_east_LOW")
        self.in_east_LOW.setGeometry(QRect(160, 120, 33, 20))
        self.out_east_LOW = QWidget(Form)
        self.out_east_LOW.setObjectName(u"out_east_LOW")
        self.out_east_LOW.setGeometry(QRect(160, 110, 33, 6))
        self.in_south_LOW = QWidget(Form)
        self.in_south_LOW.setObjectName(u"in_south_LOW")
        self.in_south_LOW.setGeometry(QRect(50, 160, 20, 30))
        self.out_south_LOW = QWidget(Form)
        self.out_south_LOW.setObjectName(u"out_south_LOW")
        self.out_south_LOW.setGeometry(QRect(72, 160, 6, 30))
        self.in_south_HIGH = QWidget(Form)
        self.in_south_HIGH.setObjectName(u"in_south_HIGH")
        self.in_south_HIGH.setGeometry(QRect(108, 160, 20, 30))
        self.out_south_HIGH = QWidget(Form)
        self.out_south_HIGH.setObjectName(u"out_south_HIGH")
        self.out_south_HIGH.setGeometry(QRect(131, 160, 6, 30))
        self.out_weast_LOW = QWidget(Form)
        self.out_weast_LOW.setObjectName(u"out_weast_LOW")
        self.out_weast_LOW.setGeometry(QRect(0, 127, 30, 6))
        self.in_weast_LOW = QWidget(Form)
        self.in_weast_LOW.setObjectName(u"in_weast_LOW")
        self.in_weast_LOW.setGeometry(QRect(0, 103, 30, 20))
        self.in_east_HIGH = QWidget(Form)
        self.in_east_HIGH.setObjectName(u"in_east_HIGH")
        self.in_east_HIGH.setGeometry(QRect(160, 70, 20, 20))
        self.out_east_HIGH = QWidget(Form)
        self.out_east_HIGH.setObjectName(u"out_east_HIGH")
        self.out_east_HIGH.setGeometry(QRect(160, 60, 33, 6))
        self.out_north_LOW = QWidget(Form)
        self.out_north_LOW.setObjectName(u"out_north_LOW")
        self.out_north_LOW.setGeometry(QRect(57, 0, 6, 30))
        self.in_north_LOW = QWidget(Form)
        self.in_north_LOW.setObjectName(u"in_north_LOW")
        self.in_north_LOW.setGeometry(QRect(65, 0, 20, 30))
        self.local_out = QWidget(Form)
        self.local_out.setObjectName(u"local_out")
        self.local_out.setGeometry(QRect(0, 20, 20, 20))
        self.local_Label = QLabel(Form)
        self.local_Label.setObjectName(u"local_Label")
        self.local_Label.setGeometry(QRect(20, 18, 40, 20))
        self.local_Label.setFont(font1)
        self.local_in = QWidget(Form)
        self.local_in.setObjectName(u"local_in")
        self.local_in.setGeometry(QRect(0, 0, 20, 20))

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setStyleSheet(QCoreApplication.translate("Form", u"background-color: rgb(255, 255, 255);", None))
        self.routerLabel.setText("")
        self.north_HIGH_Label.setText(QCoreApplication.translate("Form", u"00.00%", None))
        self.south_HIGH_Label.setText(QCoreApplication.translate("Form", u"00.00%", None))
        self.south_LOW_Label.setText(QCoreApplication.translate("Form", u"00.00%", None))
        self.weast_LOW_Label.setText(QCoreApplication.translate("Form", u"00.00%", None))
        self.weast_HIGH_Label.setText(QCoreApplication.translate("Form", u"00.00%", None))
        self.north_LOW_Label.setText(QCoreApplication.translate("Form", u"00.00%", None))
        self.east_HIGH_Label.setText(QCoreApplication.translate("Form", u"00.00%", None))
        self.east_LOW_Label.setText(QCoreApplication.translate("Form", u"00.00%", None))
        self.local_Label.setText(QCoreApplication.translate("Form", u"00.00%", None))
    # retranslateUi

